from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['ENABLE_PM']):
    src = src + ['pm.c']

if len(src):
    group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
