# for network related component
import os
Import('RTT_ROOT')
from building import *

objs = []
cwd = GetCurrentDir()
list = os.listdir(cwd)

# the default version of LWIP is 2.0.2
if not GetDepend('ENABLE_LWIP141') and not GetDepend('ENABLE_LWIP202') and not GetDepend('ENABLE_LWIP212'):
    AddDepend('ENABLE_LWIP202')

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
