# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Filesystem', src, depend = ['ENABLE_DFS', 'ENABLE_DFS_ELMFAT'], CPPPATH = CPPPATH)

Return('group')
