# SConscript for sensor framework 

from building import *

cwd = GetCurrentDir()
src = ['sensor.c']
CPPPATH = [cwd, cwd + '/../include']

if GetDepend('ENABLE_SENSOR_CMD'):
    src += ['sensor_cmd.c']

group = DefineGroup('Sensors', src, depend = ['ENABLE_SENSOR', 'ENABLE_DEVICE'], CPPPATH = CPPPATH)

Return('group')
