from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd + '/../include']
src     = Split('''
cputime.c
''')

if GetDepend('ENABLE_CPUTIME_CORTEXM'):
    src += ['cputime_cortexm.c']

group   = DefineGroup('DeviceDrivers', src, depend = ['ENABLE_CPUTIME'], CPPPATH = CPPPATH)

Return('group')
