################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
OBJCOPY_HEX := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
api/api/src \
api/drivers/can \
api/drivers/hwtimer \
api/drivers/misc \
api/drivers/phy \
api/drivers/rtc \
api/drivers/sdio \
api/drivers/serial \
api/drivers/spi/sfud/src \
api/drivers/spi \
api/drivers/watchdog \
board/app \
board/app/algorithm_lib \
board/app/app_ad7606_data \
board/app/app_channel_switch \
board/app/app_cominform_config \
board/app/app_data_save \
board/app/app_diagnosis \
board/app/app_iwdg \
board/app/app_led_control \
board/app/app_multicast_thread \
board/app/app_paras_config \
board/app/app_paras_save \
board/app/app_protocol_file \
board/app/app_pwm \
board/app/app_self_test \
board/app/app_send_record \
board/app/app_singlecast_thread \
board/app/app_tftp_up_raw \
board/app/app_timer \
board/app/app_utility \
board/app/recv_test \
board/app/recv_test/net \
board/device/flash \
board/device/phy \
board/device/sdcard \
board/device/sram \
board/fs \
board/lh/algorithm \
board/lh/itc \
board/lh/util \
board/module/ad7606 \
board/module/can \
board/module/config \
board/module/diagnosis \
board/module/iap \
board/module/led \
board/module/switch \
board/net \
board/project/tfdsn/msp/cortex-m4 \
bsp/internal_ad7606 \
bsp/internal_flash \
bsp/internal_led_control \
bsp/internal_timer \
bsp/stm32/drivers \
bsp/stm32/drivers/drv_flash \
fs/devfs \
fs/dfs/src \
fs/elmfat \
fs/romfs \
lib/common \
lib/dsp/source/BasicMathFunctions \
lib/dsp/source/CommonTables \
lib/dsp/source/ComplexMathFunctions \
lib/dsp/source/ControllerFunctions \
lib/dsp/source/FastMathFunctions \
lib/dsp/source/FilteringFunctions \
lib/dsp/source/MatrixFunctions \
lib/dsp/source/StatisticsFunctions \
lib/dsp/source/SupportFunctions \
lib/dsp/source/TransformFunctions \
lib/newlib \
net/lwip-2.1.2/src/api \
net/lwip-2.1.2/src/apps/ping \
net/lwip-2.1.2/src/apps/tftp \
net/lwip-2.1.2/src/arch \
net/lwip-2.1.2/src/core \
net/lwip-2.1.2/src/core/ipv4 \
net/lwip-2.1.2/src/core/ipv6 \
net/lwip-2.1.2/src/netif \
net/lwip-2.1.2/src/netif/ppp \
net/lwip-2.1.2/src/netif/ppp/polarssl \
net/netdev/src \
net/netutils/iperf \
net/netutils/netio \
net/netutils/ntp \
net/netutils/ping \
net/netutils/tcpdump \
net/netutils/telnet \
net/netutils/tftp \
rtos/libcpu/arm/common \
rtos/libcpu/arm/cortex-m4 \
rtos/src \
usr/finsh \
usr/ini \

