from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd + '/../include']
group   = DefineGroup('DeviceDrivers', src, depend = ['ENABLE_WDT'], CPPPATH = CPPPATH)

Return('group')
