from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd + '/../include']
group = DefineGroup('DeviceDrivers', src, depend = ['ENABLE_PHY'], CPPPATH = CPPPATH)

Return('group')
