from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd + '/../include']

if not GetDepend('ENABLE_MEMORY_HEAP'):
    SrcRemove(src, 'dataqueue.c')
    SrcRemove(src, 'pipe.c')

group = DefineGroup('DeviceDrivers', src, depend = ['ENABLE_DEVICE_IPC'], CPPPATH = CPPPATH)

Return('group')
