from building import *
Import('rtconfig')

src   = Glob('*.c') + Glob('*.cpp')
cwd   = GetCurrentDir()
group = []

CPPPATH = [cwd]
CPPDEFINES = ['ENABLE_ARM_LIBC']

if GetDepend('ENABLE_DFS') == False:
    SrcRemove(src, ['stdio.c'])

if GetDepend('ENABLE_MODULE') == False:
    SrcRemove(src, ['libc_syms.c'])

if rtconfig.PLATFORM == 'armcc' or rtconfig.PLATFORM == 'armclang':
    group = DefineGroup('libc', src, depend = ['ENABLE_LIBC'], 
        CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
