from building import *

cwd = GetCurrentDir()
src = []
depend = []

CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['ENABLE_MTD_NOR']):
    src += ['mtd_nor.c']
    depend += ['ENABLE_MTD_NOR']

if GetDepend(['ENABLE_MTD_NAND']):
    src += ['mtd_nand.c']
    depend += ['ENABLE_MTD_NAND']

if src:
    group = DefineGroup('DeviceDrivers', src, depend = depend, CPPPATH = CPPPATH)

Return('group')
