from building import *
Import('rtconfig')

src = Glob('*.c') + Glob('*.cpp')
cwd = GetCurrentDir()
group = []

CPPPATH = [cwd]
CPPDEFINES = ['ENABLE_MINILIBC']

if rtconfig.PLATFORM == 'gcc' and rtconfig.ARCH != 'sim' and not GetDepend('ENABLE_LIBC') and GetDepend('ENABLE_MINILIBC'):
    group = DefineGroup('libc', src, depend = [''],
        CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
